/*
 * Konkod
 * Kontrol Kodu
 *
 * OpenAPI spec version: v1
 * Contact: mkilcibkm@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Konkod
 */

public class Konkod {
  public static final String SERIALIZED_NAME_KONKOD_ID = "konkodId";
  @SerializedName(SERIALIZED_NAME_KONKOD_ID)
  private Long konkodId;

  public static final String SERIALIZED_NAME_STATUS_ID = "statusId";
  @SerializedName(SERIALIZED_NAME_STATUS_ID)
  private Long statusId;

  public static final String SERIALIZED_NAME_INSTUTION_NAME = "instutionName";
  @SerializedName(SERIALIZED_NAME_INSTUTION_NAME)
  private String instutionName;

  public static final String SERIALIZED_NAME_IMAGE = "image";
  @SerializedName(SERIALIZED_NAME_IMAGE)
  private String image;

  public static final String SERIALIZED_NAME_DEPARTMAN = "departman";
  @SerializedName(SERIALIZED_NAME_DEPARTMAN)
  private String departman;

  public static final String SERIALIZED_NAME_PERSON = "person";
  @SerializedName(SERIALIZED_NAME_PERSON)
  private String person;

  public static final String SERIALIZED_NAME_CODE = "code";
  @SerializedName(SERIALIZED_NAME_CODE)
  private String code;

  public static final String SERIALIZED_NAME_INSERTION_DATE = "insertionDate";
  @SerializedName(SERIALIZED_NAME_INSERTION_DATE)
  private String insertionDate;

  public static final String SERIALIZED_NAME_UPDATED_DATE = "updatedDate";
  @SerializedName(SERIALIZED_NAME_UPDATED_DATE)
  private String updatedDate;

  public static final String SERIALIZED_NAME_STAR1 = "star1";
  @SerializedName(SERIALIZED_NAME_STAR1)
  private Long star1;

  public static final String SERIALIZED_NAME_STAR2 = "star2";
  @SerializedName(SERIALIZED_NAME_STAR2)
  private Long star2;

  public static final String SERIALIZED_NAME_STAR3 = "star3";
  @SerializedName(SERIALIZED_NAME_STAR3)
  private Long star3;

  public Konkod konkodId(Long konkodId) {
    this.konkodId = konkodId;
    return this;
  }

   /**
   * Get konkodId
   * @return konkodId
  **/
  @ApiModelProperty(value = "")
  public Long getKonkodId() {
    return konkodId;
  }

  public void setKonkodId(Long konkodId) {
    this.konkodId = konkodId;
  }

  public Konkod statusId(Long statusId) {
    this.statusId = statusId;
    return this;
  }

   /**
   * Get statusId
   * @return statusId
  **/
  @ApiModelProperty(value = "")
  public Long getStatusId() {
    return statusId;
  }

  public void setStatusId(Long statusId) {
    this.statusId = statusId;
  }

  public Konkod instutionName(String instutionName) {
    this.instutionName = instutionName;
    return this;
  }

   /**
   * Get instutionName
   * @return instutionName
  **/
  @ApiModelProperty(value = "")
  public String getInstutionName() {
    return instutionName;
  }

  public void setInstutionName(String instutionName) {
    this.instutionName = instutionName;
  }

  public Konkod image(String image) {
    this.image = image;
    return this;
  }

   /**
   * Get image
   * @return image
  **/
  @ApiModelProperty(value = "")
  public String getImage() {
    return image;
  }

  public void setImage(String image) {
    this.image = image;
  }

  public Konkod departman(String departman) {
    this.departman = departman;
    return this;
  }

   /**
   * Get departman
   * @return departman
  **/
  @ApiModelProperty(value = "")
  public String getDepartman() {
    return departman;
  }

  public void setDepartman(String departman) {
    this.departman = departman;
  }

  public Konkod person(String person) {
    this.person = person;
    return this;
  }

   /**
   * Get person
   * @return person
  **/
  @ApiModelProperty(value = "")
  public String getPerson() {
    return person;
  }

  public void setPerson(String person) {
    this.person = person;
  }

  public Konkod code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @ApiModelProperty(value = "")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public Konkod insertionDate(String insertionDate) {
    this.insertionDate = insertionDate;
    return this;
  }

   /**
   * Get insertionDate
   * @return insertionDate
  **/
  @ApiModelProperty(value = "")
  public String getInsertionDate() {
    return insertionDate;
  }

  public void setInsertionDate(String insertionDate) {
    this.insertionDate = insertionDate;
  }

  public Konkod updatedDate(String updatedDate) {
    this.updatedDate = updatedDate;
    return this;
  }

   /**
   * Get updatedDate
   * @return updatedDate
  **/
  @ApiModelProperty(value = "")
  public String getUpdatedDate() {
    return updatedDate;
  }

  public void setUpdatedDate(String updatedDate) {
    this.updatedDate = updatedDate;
  }

  public Konkod star1(Long star1) {
    this.star1 = star1;
    return this;
  }

   /**
   * Get star1
   * @return star1
  **/
  @ApiModelProperty(value = "")
  public Long getStar1() {
    return star1;
  }

  public void setStar1(Long star1) {
    this.star1 = star1;
  }

  public Konkod star2(Long star2) {
    this.star2 = star2;
    return this;
  }

   /**
   * Get star2
   * @return star2
  **/
  @ApiModelProperty(value = "")
  public Long getStar2() {
    return star2;
  }

  public void setStar2(Long star2) {
    this.star2 = star2;
  }

  public Konkod star3(Long star3) {
    this.star3 = star3;
    return this;
  }

   /**
   * Get star3
   * @return star3
  **/
  @ApiModelProperty(value = "")
  public Long getStar3() {
    return star3;
  }

  public void setStar3(Long star3) {
    this.star3 = star3;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Konkod konkod = (Konkod) o;
    return Objects.equals(this.konkodId, konkod.konkodId) &&
        Objects.equals(this.statusId, konkod.statusId) &&
        Objects.equals(this.instutionName, konkod.instutionName) &&
        Objects.equals(this.image, konkod.image) &&
        Objects.equals(this.departman, konkod.departman) &&
        Objects.equals(this.person, konkod.person) &&
        Objects.equals(this.code, konkod.code) &&
        Objects.equals(this.insertionDate, konkod.insertionDate) &&
        Objects.equals(this.updatedDate, konkod.updatedDate) &&
        Objects.equals(this.star1, konkod.star1) &&
        Objects.equals(this.star2, konkod.star2) &&
        Objects.equals(this.star3, konkod.star3);
  }

  @Override
  public int hashCode() {
    return Objects.hash(konkodId, statusId, instutionName, image, departman, person, code, insertionDate, updatedDate, star1, star2, star3);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Konkod {\n");
    
    sb.append("    konkodId: ").append(toIndentedString(konkodId)).append("\n");
    sb.append("    statusId: ").append(toIndentedString(statusId)).append("\n");
    sb.append("    instutionName: ").append(toIndentedString(instutionName)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    departman: ").append(toIndentedString(departman)).append("\n");
    sb.append("    person: ").append(toIndentedString(person)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    insertionDate: ").append(toIndentedString(insertionDate)).append("\n");
    sb.append("    updatedDate: ").append(toIndentedString(updatedDate)).append("\n");
    sb.append("    star1: ").append(toIndentedString(star1)).append("\n");
    sb.append("    star2: ").append(toIndentedString(star2)).append("\n");
    sb.append("    star3: ").append(toIndentedString(star3)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

