/*
 * Konkod
 * Kontrol Kodu
 *
 * OpenAPI spec version: v1
 * Contact: mkilcibkm@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.junit.Assert;
import org.openapitools.client.ApiException;
import org.openapitools.client.model.ClientCredentials;
import org.openapitools.client.model.JWTToken;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AuthenticationApi
 */

public class AuthenticationApiTest {

    private final AuthenticationApi api = new AuthenticationApi();


    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void authenticationPOSTTest() throws ApiException {
        JWTToken response = authenticate(createClientCredentials());
        System.out.println("response:" + response);
        // TODO: test validations
        Assert.assertNotNull(response);
    }

    public JWTToken authenticate(ClientCredentials clientCredentials) throws ApiException {
        return api.authenticationPOST(clientCredentials);
    }

    public ClientCredentials createClientCredentials(){
        ClientCredentials clientCredentials = new ClientCredentials();
        clientCredentials.setClientId("client_id");
        clientCredentials.setClientSecret("client_secret");
        clientCredentials.setGrantType("grant_type");
        return clientCredentials;
    }

}
