/*
 * Konkod
 * Kontrol Kodu
 *
 * OpenAPI spec version: v1
 * Contact: mkilcibkm@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.junit.Assert;
import org.openapitools.client.ApiException;
import org.openapitools.client.model.User;
import org.junit.Test;
import org.junit.Ignore;

import java.util.*;

/**
 * API tests for UserApi
 */

public class UserApiTest {

    private final UserApi api = new UserApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void userPOSTTest() throws ApiException {
        User user = new User();
        user.setPhone("5325858842");
        user.setFcmRegistrationId("seren");
        User response = api.userPOST(user);
        System.out.println("response:" + response);
        // TODO: test validations
        Assert.assertNotNull(response);
    }
    
}
